name: CI

on:
  push:
    branches:
      - master
      - 'v*'
  pull_request:
  schedule:
    - cron: '0 3 * * *' # daily, at 3am

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test:ember
        working-directory: test-app

  floating-dependencies:
    name: 'Floating Dependencies'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - run: yarn install --no-lockfile
      - run: yarn test:ember
        working-directory: test-app

  try-scenarios:
    name: 'Try: ${{ matrix.ember-try-scenario }}'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    needs: test

    strategy:
      fail-fast: true
      matrix:
        ember-try-scenario:
          - ember-lts-3.28
          - ember-lts-4.4
          - ember-lts-4.8
          - ember-release
          - ember-beta
          - ember-canary
          - embroider-safe
          - embroider-optimized

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: test
        run: node_modules/.bin/ember try:one ${{ matrix.ember-try-scenario }} --skip-cleanup
        working-directory: test-app

  types:
    runs-on: ubuntu-latest

    needs: test

    strategy:
      fail-fast: false
      matrix:
        ts-version:
          - 4.8
          - 4.9
          - next

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v4
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: install TS version
        run: yarn install --dev typescript@${{matrix.ts-version}}
        working-directory: addon
      - name: test types
        run: yarn test:types
        working-directory: addon
